import Header from '@/components/layouts/Header'
import './globals.css'
import { Roboto } from 'next/font/google'

import Footer from '@/components/layouts/Footer'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header >Header Component</Header>
        {/* <Aside /> */}

        {children}
        <Footer>Footer Component</Footer>
      </body>
    </html >
  )
}
